### ISSUE TITLE
새로운 스터디 오픈 되었을 때, 하이라이팅

### ISSUE THREAD

**Issue by Universe1122** [CASPER-REPSAC/casper-api#34]
새로운 스터디가 오픈 되었을 때, "NEW" 라는 키워드를 붙여 줬으면 좋겠음
예를들어, 게시판에 새로운 글이 올라오면 게시글 제목 옆에 "NEW" 라는 키워드가 추가되는 방식으로..

NEW 키워드는 최소 2일 정도 유지 되었으면 함.

**Comment by FoO-511** [comment]
게시글 제목 옆은 너무 공간이 좁아 그 아래에 뱃지를 달았습니다.
뱃지 형태 등 수정을 바라면 아래에 코멘트 남겨주세요
