### ISSUE TITLE
새로운 tag가 생기지 않음

### ISSUE THREAD

**Issue by FoO-511** [CASPER-REPSAC/casper-api#7]

**Comment by FoO-511** [comment]
activity작성 요청을 하면 activitiy는 생기지만 tags는 생기지 않음
요청 데이터: 
```
{
    "title": "test1104",
    "type": "Study",
    "author": "casper",
    "createDate": "2021-11-04",
    "description": "test project",
    "startDate": "2021-11-04",
    "endDate": "2021-11-04",
    "currentState": 0,
    "viewerNum": 0,
    "tags": [
        "casper",
        "dd"
    ],
    "participants": [
        "parti1"
    ]
}
```

**Comment by woohyun212** [comment]
Tag 생성하고 글에 붙이는 건  좀 절차가 복잡함
http://3.36.158.99:30009/api/tags/ 여기에서 새로운 태그 생성하고
`{
    "name": "NewTag"
}`
http://3.36.158.99:30009/api/actitags/ 여기에서 activity_id 랑 tag_id 랑 연결 지으면
`{
    "activity_id": 40,
    "tag_id": 1
}`
나중에 activity list에서 tag가 불러와져서 보이게 됨

**Comment by woohyun212** [comment]
### 본영이 요청 사항
`http://127.0.0.1:8000/api/activities/` 으로 activity 를 생성할 때,
Tags 에 tag 를 담아보내면 태그가 생성안됨.
tag 등록을 위해 너무 많은 요청을 보내야함, 불편함.

`http://127.0.0.1:8000/api/activities/ `에 요청 한번으로 태그 추가까지 한번에 처리 되었으면 좋겠음

**Comment by woohyun212** [comment]
activity_list 의 post 부분을 수정하여 해결함.
![image](https://user-images.githubusercontent.com/43837268/140563268-b0a1c87f-80a5-40d2-8fda-6b40c7363c29.png)
tag는 리스트로 입력받는게 프론트에서 편해보여서, 리스트로 설계함.
![image](https://user-images.githubusercontent.com/43837268/140563091-54eb3fc3-9f0b-49f5-ba56-84fa411aaa68.png)
<해결>
